### ISSUE TITLE
Date-fns.org website cannot work and display "Failed to fetch version list"

### ISSUE THREAD

**Issue by Mark24Code** [date-fns/date-fns.org#115]
Date-fns.org website cannot work and display "Failed to fetch version list".

**Comment by kossnocorp** [comment]
@Mark24Code I assume that you're trying to access it from China. The thing is that some Chinese ISPs block Firebase database IPs and that's why you can't load it. This is a recurring problem, and I don't know a solution for it. If you know a Chinese person/company that knows how to solve the problem and wants to help, please tell me.
