### ISSUE TITLE
Add comparison doc (date-fns vs Moment.js)

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns.org#82]

**Comment by albertorestifo** [comment]
I can help with that. I've been using Moment.js for ages.

What if instead of being a "comparison doc" is more like a "moving from moment" doc?

Something the likes of:

## Time from now

The equivalent of `moment#fromNow` is [`distanceInWordsToNow`](https://date-fns.org/docs/distanceInWordsToNow).

Note that by default Moment includes the suffix. To get the same behaviour in date-fns you need to set the `addSuffix` option to `true`.

**Moment.js**

```js
moment([2016, 10, 23]).fromNow(); // 8 days ago
```

**date-fns**

```js
import distanceInWordsToNow from 'date-fns/distance_in_words_to_now'

distanceInWordsToNow(new Date(2016, 10, 23), { addSuffix: true }); // 8 days ago
```

**Comment by leshakoss** [comment]
Years passed, moment.js seems like not a factor anymore, and we probably don't want to spend time on this. Closing this 🤷‍♂️

**Comment by kossnocorp** [comment]
You're right!

**Comment by Tokenyet** [comment]
Update for this issue:

```
import { formatDistanceToNow } from 'date-fns';
```

There is no `distanceInWordsToNow`, but `formatDistanceToNow `.
